version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: YOURPASSWORD
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
  admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: YOUREMAIL
      PGADMIN_DEFAULT_PASSWORD: YOURPASSWORD
    ports:
      - 8080:80
    volumes:
      - admin-data:/var/lib/pgadmin
volumes:
  db-data:
  admin-data:


